import React from "react";
import { Container } from "react-bootstrap";

function PaymentReturns(){
    return(
        <div>
            <Container>
                <h3 style={{marginTop:"20px"}}>Payment & Returns</h3>
                <p>MahavirElectronics.net thanks you and values your purchase with us. This section describes MahavirElectronics.net’s policies on payments received from customers and returns to customers for products or services ordered.</p>
                <h4><b>1.Acceptable Methods Of Payment</b></h4>
                <p>Presently payment methods available with MahavirElectronics.net are through Credit Cards, Debit Cards and Net banking only. As and when other methods will be incorporated, the same would be updated here as well. Your Credit/Debit card information remains private and confidential. MahavirElectronics.net and our secure online payment gateways use Secure Sockets Layer security technology to protect your Card information. We accept all VISA & MasterCards– only Indian cards, as International cards would not be supported. You will have to enter your 16 digit Credit/Debit card number and the 3 digit CVV (Card Verification Value) code which is at the back of your card and complete the payment.</p>
                <h4><b>2.Verified By VISA (VBV) and MasterCard Secure Code</b></h4>
                <p>Presently payment methods available with MahavirElectronics.net are through Credit Cards, Debit Cards and Net banking only. As and when other methods will be incorporated, the same would be updated here as well. Your Credit/Debit card information remains private and confidential. MahavirElectronics.net and our secure online payment gateways use Secure Sockets Layer security technology to protect your Card information. We accept all VISA & MasterCards– only Indian cards, as International cards would not be supported. You will have to enter your 16 digit Credit/Debit card number and the 3 digit CVV (Card Verification Value) code which is at the back of your card and complete the payment.</p>
                <h4><b>3.Cash On Delivery(C.O.D.)</b></h4>
                <p>Is available in Pune where our stores are located only and is valid for a maximum of Rs. 50,000 /- per transaction. Our customer has to pay the complete booked amount prior to delivery, to be collected by authorized Mahavir Electronics (INDIA) collection personnel. The official receipt for cash collected will be provided to the customer.</p>
                <h4><b>4.Pricing</b></h4>
                <p>All offer prices on MahavirElectronics.net are all inclusive; there are no hidden charges whatsoever. You have to only pay the offer price that you see on our product page next to the specific product image.</p>
                <h4><b>5.Orders</b></h4>
                <p>After placing your valued order and making the payment, we would not be able to make any changes in the same. Also combining or adding orders once they have been placed would not be possible. Post shipment of your products, orders cannot be cancelled at all. In the event of non-delivery occured due to your mistake (wrong name, address or any other wrong information), MahavirElectronics.net would incur an extra cost for redelivery and the same would be claimed from you.Any order placed for a product that is listed at an incorrect price may be cancelled. This shall be regardless of whether the order has been confirmed and/or payment levied. In the event the payment has been processed, the same shall be credited to your account and duly notified to you by email.</p>
                <h4><b>6.Demonstration & Installation</b></h4>
                <p>Demonstration is provided by the manufacturing company and is provided on certain products only, in case of further clarifications, we would request to contact us on +91 7219318080 or email us on edata@mahavirelectronics.net and we will be happy to clarify on the same. After delivery/receipt of product, the demonstration, if applicable, would happen after minimum 4 business days. Only the first demonstration would be on a complimentary basis.Installation is provided by the manufacturing company’s authorized service center/franchisee only. For Split A/C, standard installation charges will apply; payable by the consumer directly to the company’s authorized service center/franchisee.Inclusions in scope of work for Split A/c installation: - Installation of Indoor and Outdoor units, Interconnecting Indoor and Outdoor unit with piping.Exclusions in scope of work for Split A/c Installation:- All masonry work, Supply and Installation of main power phase, electrical work, Leak testing if piping is already done by the consumer, no drilling holes in any of the pillars, dismantling charges if earlier Split A/c is present.For other products, standard installation will be provided as per companies norms and is complimentary. After delivery/receipt of product, the installation would happen after minimum 4 business days. We would request you to kindly contact us on the above mentioned contact details for any assistance required.</p>
                <h4><b>7.Returns & Refunds</b></h4>
                <p>MahavirElectronics.net makes every effort to service the orders placed with them, as per the specification and delivery timelines mentioned against each product. As a policy, we request you to kindly check the product and the accessories while accepting the delivery. In case of any discrepancies, kindly bring it to our notice before accepting delivery by calling us on +91 7219318080 or email us on edata@mahavirelectronics.net. After acceptance of delivery of the product, MahavirElectronics.net will not entertain any returns or refund request.Refund will be done within 10-15 working days from the date of request of refund.After sales service is provided by the authorized service centers of the respective manufacturing companies. For product service requirement, kindly contact us on the above mentioned details for the same.For any product/service available on sale on www.mahavirelectronics.net, the company does not assume any liability. MahavirElectronics.net is only in the business of providing products/services from manufacturers to customers at the destination of their choice in Mumbai, Pune, Gujarat and Delhi. (Limited to mentioned cities limits only</p>
            </Container>
        </div>
    )
}

export default PaymentReturns;