import React from "react";
import { Container } from "react-bootstrap";

function TermsOfUse(){
    return(
        <div>
            <Container>
                <h3 style={{marginTop:"20px"}}><b>Terms Of Use</b></h3>
                <p>MahavirElectronics.net provides its services to you subject to the notices, terms, and conditions set forth in this agreement (the "Agreement"). In addition, when you use any MahavirElectronics.net service (e.g., Customer Reviews), you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they are incorporated into this Agreement by this reference. MahavirElectronics.net reserves the right to change this Site and these terms and conditions at any time.MahavirElectronics.net retains the right to deny access to anyone who we believe has violated any of these Terms of Use. If you are under 18, you may use MahavirElectronics.net only with involvement of a parent or guardian.
                <br></br>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING</p>
                <h4><b>1.Contents Posted On Site</b></h4>
                <p>You are responsible for any notes, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Sites (collectively, "Content"). Such Content will become the property of MahavirElectronics.net throughout the universe. MahavirElectronics.net shall be entitled to, consistent with our Privacy Policy, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include Content you provide. You agree that any Content you post may be used by MahavirElectronics.net, consistent with our Privacy Policy and Rules of Conduct on Site as mentioned herein, and you are not entitled to any payment or other compensation for such use.</p>
                <h4><b>2.Rules Of Conduct On Site</b></h4>
                <p>
a)
You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights.
<br></br><br></br>b)
MahavirElectronics.net may review, edit, reject, refuse to post and/or delete any Content that in the sole judgment of MahavirElectronics.net violate these Terms of Use or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of another person.
<br></br><br></br>c)
Any information provided by you on this site shall not be misleading in any way.
<br></br><br></br>d)
You may not post or transmit Content, (even if made in a joking, sarcastic or unintended manner), if it in any way:
• is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, pedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;
<br></br>• harasses or advocates harassment of another person;
<br></br>•promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
<br></br>•infringes upon or violates any third party's rights [(including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];
<br></br>•promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
<br></br>•contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
<br></br>•provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
<br></br>•provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses
<br></br>•contains video, photographs, or images of another person age 18 or older without his or her express written consent and permission or those of any minor (regardless of whether you have consent from the minor or his or her legal guardian).
<br></br>•tries to gain unauthorized access or exceeds the scope of authorized access (as defined herein and in other applicable Codes of Conduct or End User Access and License Agreements) to the Sites or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Sites or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
<br></br>•Engages in commercial activities and/or sales without Mahavi's prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" items related to the Sites. Throughout this Terms of Use,MahavirElectronics.net's "prior written consent" means a communication coming from MahavirElectronics.net's legal department, specifically in response to your request, and specifically addressing the activity or conduct for which you seek authorization;
<br></br>•solicits gambling or engages in any gambling activity which MahavirElectronics.net, in its sole discretion, believes is or could be construed as being illegal;
<br></br>•contains viruses, time bombs, trojan horses, cancelbots, worms or other harmful or deleterious components or devices;
<br></br>•interferes with another user's use and enjoyment of the Sites or any other individual's user and enjoyment of similar services; or
<br></br>•Refers to any website or URL that, in the sole discretion of MahavirElectronics.net, contains material that is inappropriate for the Sites, contains content that would be prohibited on the Sites, or violates the letter or spirit of these Terms of Use.
<br></br><br></br>e)
You must use the Sites in a manner consistent with any and all applicable laws and regulations. Illegal and/or unauthorized uses of the Sites, including without limitation, collecting usernames and/or email addresses of registered members by electronic or other means for the purpose of sending unsolicited email and unauthorized framing of or linking to the Sites, are not permitted. This includes the unauthorized interception of the data stream coming from or going into the Sites, as well as attempting to gain unauthorized access to the Sites or exceeding your authorized access.
<br></br><br></br>f)
You may not engage in advertising to, or solicitation of, other users through the Sites to buy or sell any products or services, including, but not limited to, products or services related to the Sites. You may not transmit any chain letters or unsolicited commercial or junk email to other users via the Sites. It is also a violation of these Terms of Use to use any information obtained from the Sites in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person outside of the Sites without their prior explicit consent. In order to protect our users from such advertising or solicitation, MahavirElectronics.net reserves the right to restrict the number of messages or emails which a user may send to other users in any 24-hour period to a number which MahavirElectronics.net deems appropriate in its sole discretion.
<br></br><br></br>g)
You understand that MahavirElectronics.net has the right at all times to disclose any information (including the identity of the persons providing information or materials on the Sites) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and you hereby expressly authorize us to) disclose any information about you to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
<br></br><br></br>h)
MahavirElectronics.net reserves the right, but has no obligation, to monitor the materials MahavirElectronics.net reserves the right, but has no obligation, to monitor the materials posted in the public areas of the Sites. MahavirElectronics.net shall have the right to remove or edit any Content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right of MahavirElectronics.net, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST IN THE PUBLIC AREAS OF THE SITES AND IN YOUR PRIVATE MESSAGES. Please be advised that Content posted in public areas of the Sites does not necessarily reflect the views of MahavirElectronics.net. In no event shall MahavirElectronics.net assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Sites. You hereby represent and warrant that you have all necessary rights in and to all Content you provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.
<br></br><br></br>i)
Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through the Sites, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. MahavirElectronics.net shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on the Sites.
<br></br><br></br>j)
It is possible that other users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Sites and that you may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about you due to your use of the Sites, and that the recipient may use such information to harass or injure you. MahavirElectronics.net does not approve of such unauthorized uses but by using the Sites you acknowledge and agree that MahavirElectronics.net is not responsible for the use of any personal information that you publicly disclose or share with others on the Sites. Please carefully select the type of information that you publicly disclose or share with others on the Sites.
<br></br><br></br>k)
MahavirElectronics.net shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of People, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).
<br></br><br></br>l)
You are prohibited from violating or attempting to violate the security of the site including, without limitation, (a) accessing data not intended for you or logging onto a server or an account which you are not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, "flooding," "spamming," "mail bombing" or "crashing;" (d) sending unsolicited email, including promotions and/or advertising of products or services; or (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability.</p>
                <h4><b>3.Other Business</b></h4>
                <p>MahavirElectronics.net does not take responsibility or liability or warrant including but not limited to, the actions, products, content and services on MahavirElectronics.net’s website, which are linked through including but not limited to Affiliates and sites using MahavirElectronics.net’s APIs. In addition,MahavirElectronics.net provide links to the sites of affiliated companies and certain other businesses for which, MahavirElectronics.net is not responsible for examining or evaluating the products and services offered by them, and we do not warrant the offerings of, any of these businesses or individuals or the content of their website.</p>
                <h4><b>4.Links</b></h4>
                <p>This site may contain links to other web sites or you may be linked through other web sites ("Linked Sites"). The Linked Sites are for your convenience only and you access them at your own risk. We are not responsible for the content of the Linked Sites, whether or not MahavirElectronics.net is affiliated with sponsors of the sites.
                <br></br>
We do not in any way endorse the Linked Sites.
                <br></br>
We welcome links to this site. You may establish a hypertext link to this site, provided that the link does not state or imply any sponsorship or endorsement of your site by MahavirElectronics.net. You must not use on your site or in any other manner any trademarks, service marks or any other materials appearing on the MahavirElectronics.net site, including any logos or characters, without the express written consent of the owner of the mark or materials. You must not frame or otherwise incorporate into another web site or present in conjunction with or juxtaposed against such a web site any of the content or other materials on the MahavirElectronics.net site without our prior written consent.</p>
                <h4><b>5.Privacy</b></h4>
                <p>Use of the Site is governed by our Privacy Policy, which can be located at Privacy Policy</p>
                <h4><b>6.Mandatory Declaration - Computers</b></h4>
                <p>1)
Use of the Site is governed by our Privacy Policy, which can be located at Privacy Policy<br></br>
2)
You further declare that the Product will be acquired for personal use of the Consignee and/or Buyer. The Product will not be sold, resold, bartered or in any way disposed for profit.</p>
                <h4><b>7.Applicable Law</b></h4>
                <p>This Agreement shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be in Mumbai.</p>
                <h4><b>8.Jurisdictional Issues/Sales In India Only</b></h4>
                <p>Unless otherwise specified, the material on MahavirElectronics.net is presented solely for the purpose of sale India. MahavirElectronics.net makes no representation that materials in MahavirElectronics.net are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and MahavirElectronics.net is not responsible for supply of goods/refund for the goods ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.</p>
                <h4><b>9.Trademark,Copyright and Restriction</b></h4>
                <p>This site is controlled and operated by MahavirElectronics.net. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights that are owned and controlled by us or by other parties that have licensed their material to us. Material on MahavirElectronics.net web site owned, operated, licensed or controlled by us is solely for your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by e-mail or other electronic means and whether directly or indirectly and you must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other web site or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which you receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>
                <h4><b>10.Your Account</b></h4>
                <p>You agree that any use on the site is at your own risk and MahavirElectronics.net is not responsible for it. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. Products sold on MahavirElectronics.net are not for people below aged 18, however any products available for children below age 18, can be bought by adults.</p>
                <h4><b>11.Copyright complaint</b></h4>
                <p>We at MahavirElectronics.net respect the intellectual property of others. In case you feel that your work has been copied in a way that constitutes copyright infringement you can write to us at cs@MahavirElectronics.net</p>
                <h4><b>12.Risk Of Loss</b></h4>
                <p>All items purchased from MahavirElectronics.net are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon our delivery to the carrier.</p>
                <h4><b>13.Product Description</b></h4>
                <p>MahavirElectronics.net tries to be as accurate as possible. However, MahavirElectronics.net does not warrant that product description or other content of this site is accurate, complete, reliable, current, or error-free. If a product offered by MahavirElectronics.net itself is not as described, your sole remedy is to return it in unused condition.</p>
                <h4><b>14.Pricing/Typographical error</b></h4>
                <p>Pricing on the product is as it shows, however due to any technical issue, typographical error or product information received from our suppliers' prices of the product may vary. The price taken into consideration will be at the time of order confirmation and payment done by the customer. If MahavirElectronics.net comes across any such difference in pricing due to any issues, it has all the rights to rectify the same or cancel the order.</p>
                <h4><b>15.Credit Card use</b></h4>
                <p>In a credit/debit card transaction you must use your own credit/debit card. MahavirElectronics.net will not be liable for any credit card fraud. The liability to use a card fraudently will be on the user and the onus to “prove otherwise” will be exclusively on the user. MahavirElectronics.net.You further agree and undertake to provide the correct and valid credit card details to MahavirElectronics.net
                    <br></br>
MahavirElectronics.net reserves the right to cancel any order placed using credit card which holds International billing address.</p>
                <h4><b>16.Objectionable Material</b></h4>
                <p>You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that to the fullest extent permitted under applicable law, MahavirElectronics.net and its affiliates shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable to you.</p>
                <h4><b>17.Communication With Users</b></h4>
                <p>MahavirElectronics.net reserves the right to communicate with Users regarding this site and the User’s use of this site or any product or service purchased by the user on this site.</p>
                <h4><b>18.Our Contact</b></h4>
                <p>Please send any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Site to onlinesupport@MahavirElectronics.net</p>
                <h4><b>19.Indemnity</b></h4>
                <p>You agree to defend, indemnify and hold harmless MahavirElectronics.net, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to MahavirElectronics.net or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.</p>
                <h4><b></b></h4>
                <p></p>
            </Container>
        </div>
    )
}

export default TermsOfUse;